### ISSUE TITLE
Configuration compatibility with NGINX

### ISSUE THREAD

**Issue by blueskyjunkie** [memorysafety/river#4]
Having configuration compatibility with NGINX would enable easier migration for users.

If runtime configuration is not acceptable, perhaps a separate translator utility would still be useful.

**Comment by bdaehlie** [comment]
I wouldn't be in favor of making Nginx configs the default because that would probably end up creating architectural constraints and limitations are not ideal or difficult to satisfy. It would also prevent us from offering something better by default. However, a translation tool is probably a nice idea.

**Comment by eaufavor** [comment]
A translation tool is definitely more appealing than native support for nginx configuration.

**Comment by bdaehlie** [comment]
I filed issue #5 about a tool to handle the translation. Closing this out in favor of that.
